/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as TierlistImport } from "./routes/tierlist";
import { Route as RosterImport } from "./routes/roster";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const TierlistRoute = TierlistImport.update({
  path: "/tierlist",
  getParentRoute: () => rootRoute,
} as any);

const RosterRoute = RosterImport.update({
  path: "/roster",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/roster": {
      id: "/roster";
      path: "/roster";
      fullPath: "/roster";
      preLoaderRoute: typeof RosterImport;
      parentRoute: typeof rootRoute;
    };
    "/tierlist": {
      id: "/tierlist";
      path: "/tierlist";
      fullPath: "/tierlist";
      preLoaderRoute: typeof TierlistImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  RosterRoute,
  TierlistRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/roster",
        "/tierlist"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/roster": {
      "filePath": "roster.jsx"
    },
    "/tierlist": {
      "filePath": "tierlist.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
